// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/svanellewee/todoclient/models"
)

// PostTaskReader is a Reader for the PostTask structure.
type PostTaskReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostTaskReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostTaskCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostTaskDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostTaskCreated creates a PostTaskCreated with default headers values
func NewPostTaskCreated() *PostTaskCreated {
	return &PostTaskCreated{}
}

/* PostTaskCreated describes a response with status code 201, with default header values.

created one
*/
type PostTaskCreated struct {
	Payload *models.Task
}

func (o *PostTaskCreated) Error() string {
	return fmt.Sprintf("[POST /task/][%d] postTaskCreated  %+v", 201, o.Payload)
}
func (o *PostTaskCreated) GetPayload() *models.Task {
	return o.Payload
}

func (o *PostTaskCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Task)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostTaskDefault creates a PostTaskDefault with default headers values
func NewPostTaskDefault(code int) *PostTaskDefault {
	return &PostTaskDefault{
		_statusCode: code,
	}
}

/* PostTaskDefault describes a response with status code -1, with default header values.

could not create
*/
type PostTaskDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post task default response
func (o *PostTaskDefault) Code() int {
	return o._statusCode
}

func (o *PostTaskDefault) Error() string {
	return fmt.Sprintf("[POST /task/][%d] PostTask default  %+v", o._statusCode, o.Payload)
}
func (o *PostTaskDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostTaskDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
