// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Remember to do stuff",
    "title": "TodoServer",
    "version": "0.1.0"
  },
  "paths": {
    "/task/": {
      "get": {
        "responses": {
          "200": {
            "description": "get all the tasks",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/task"
              }
            }
          },
          "default": {
            "description": "error occurred getting tasks",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/task"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "created one",
            "schema": {
              "$ref": "#/definitions/task"
            }
          },
          "default": {
            "description": "could not create",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/task/{id}": {
      "get": {
        "responses": {
          "200": {
            "description": "got one task",
            "schema": {
              "$ref": "#/definitions/task"
            }
          },
          "default": {
            "description": "error occurred getting one task",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "operationId": "updateOne",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/task"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "updated task",
            "schema": {
              "$ref": "#/definitions/task"
            }
          },
          "default": {
            "description": "could not update task",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "task": {
      "type": "object",
      "required": [
        "description"
      ],
      "properties": {
        "completed": {
          "type": "boolean"
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Remember to do stuff",
    "title": "TodoServer",
    "version": "0.1.0"
  },
  "paths": {
    "/task/": {
      "get": {
        "responses": {
          "200": {
            "description": "get all the tasks",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/task"
              }
            }
          },
          "default": {
            "description": "error occurred getting tasks",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/task"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "created one",
            "schema": {
              "$ref": "#/definitions/task"
            }
          },
          "default": {
            "description": "could not create",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/task/{id}": {
      "get": {
        "responses": {
          "200": {
            "description": "got one task",
            "schema": {
              "$ref": "#/definitions/task"
            }
          },
          "default": {
            "description": "error occurred getting one task",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "operationId": "updateOne",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/task"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "updated task",
            "schema": {
              "$ref": "#/definitions/task"
            }
          },
          "default": {
            "description": "could not update task",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "task": {
      "type": "object",
      "required": [
        "description"
      ],
      "properties": {
        "completed": {
          "type": "boolean"
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        }
      }
    }
  }
}`))
}
