consumes:
- application/json
info:
  description: Remember to do stuff
  title: TodoServer
  version: 0.1.0
produces:
- application/json
schemes:
- http
swagger: "2.0"
definitions:
  task:
    type: object
    required:
      - description
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        type: string
        minLength: 1
      completed:
        type: boolean
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
      message:
        type: string
paths:
  /task/:
    post:
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/task"
      responses:
        201:
          description: created one
          schema:
            $ref: "#/definitions/task"
        default:
          description: could not create
          schema:
            $ref: "#/definitions/error"
    get:
      responses:
        200:
          description: get all the tasks
          schema:
            type: array
            items:
              $ref: "#/definitions/task"
        default:
          description: error occurred getting tasks
          schema:
            $ref: "#/definitions/error"
  /task/{id}:
    parameters:
      - name: id
        in: path
        type: integer
        format: int64
        required: true
    put:
      operationId: updateOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/task"
      responses:
        200:
          description: updated task
          schema:
            $ref: "#/definitions/task"
        default:
          description: could not update task
          schema:
            $ref: "#/definitions/error"
    get:
      responses:
        200:
          description: got one task
          schema:
            $ref: "#/definitions/task"
        default:
          description: error occurred getting one task
          schema:
            $ref: "#/definitions/error"
