// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/svanellewee/todoserver/models"
)

// GetTaskIDOKCode is the HTTP code returned for type GetTaskIDOK
const GetTaskIDOKCode int = 200

/*GetTaskIDOK got one task

swagger:response getTaskIdOK
*/
type GetTaskIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Task `json:"body,omitempty"`
}

// NewGetTaskIDOK creates GetTaskIDOK with default headers values
func NewGetTaskIDOK() *GetTaskIDOK {

	return &GetTaskIDOK{}
}

// WithPayload adds the payload to the get task Id o k response
func (o *GetTaskIDOK) WithPayload(payload *models.Task) *GetTaskIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get task Id o k response
func (o *GetTaskIDOK) SetPayload(payload *models.Task) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTaskIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetTaskIDDefault error occurred getting one task

swagger:response getTaskIdDefault
*/
type GetTaskIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTaskIDDefault creates GetTaskIDDefault with default headers values
func NewGetTaskIDDefault(code int) *GetTaskIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetTaskIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get task ID default response
func (o *GetTaskIDDefault) WithStatusCode(code int) *GetTaskIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get task ID default response
func (o *GetTaskIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get task ID default response
func (o *GetTaskIDDefault) WithPayload(payload *models.Error) *GetTaskIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get task ID default response
func (o *GetTaskIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTaskIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
